--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)




--
-- Name: app_users; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.app_users (
    username character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    reset_token character varying(255),
    reset_token_expiry timestamp(6) without time zone
);



--
-- Name: budget_events; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.budget_events (
    id character varying(255) NOT NULL,
    amount numeric(38,2),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    duration_months integer,
    event_date date NOT NULL,
    type character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    year_month character varying(255),
    category character varying(255),
    CONSTRAINT budget_events_type_check CHECK (((type)::text = ANY ((ARRAY['INCOME'::character varying, 'EXPENSE'::character varying, 'DEBT_CREATED'::character varying, 'DEBT_REMOVED'::character varying, 'FLEXIA_SET'::character varying, 'FLEXIA_REMOVED'::character varying, 'SUBSCRIPTION_ADDED'::character varying, 'SUBSCRIPTION_REMOVED'::character varying, 'MONTHLY_CLOSE'::character varying, 'BALANCE_CARRYOVER'::character varying])::text[])))
);



--
-- Name: calendar_events; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.calendar_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_date date NOT NULL,
    title character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    event_time time(0) without time zone,
    event_type character varying(255),
    reminder_minutes integer,
    CONSTRAINT calendar_events_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['WORK'::character varying, 'PERSONAL'::character varying, 'HEALTH'::character varying, 'FINANCE'::character varying, 'STUDY'::character varying, 'FUN'::character varying])::text[])))
);



--
-- Name: calendar_events_id_seq; Type: SEQUENCE; Schema: public; Owner: budget
--

ALTER TABLE public.calendar_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_limits; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.category_limits (
    id character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    monthly_limit numeric(38,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(255) NOT NULL
);



--
-- Name: savings_goal_transactions; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.savings_goal_transactions (
    id character varying(255) NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_id character varying(255),
    note character varying(255),
    savings_goal_id character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);



--
-- Name: savings_goals; Type: TABLE; Schema: public; Owner: budget
--

CREATE TABLE public.savings_goals (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    current_amount numeric(38,2) NOT NULL,
    icon character varying(255),
    name character varying(255) NOT NULL,
    target_amount numeric(38,2) NOT NULL,
    target_date date,
    username character varying(255) NOT NULL
);



--
-- Data for Name: app_users; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('kat', '2026-06-29 12:05:28.382008', 'katiavalentini99@gmail.com', '$2a$10$drMiQiivp1tbtVWOSClO0uHDKUc6Ya7O5WahdMlbC0/6rYXg5mElO', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('giovanni', '2026-06-29 14:57:10.130818', 'mario@budget.com', '$2a$10$.76VGcQApcumBH3ccxFzEuLklk4S04i5WbogYOqE/ChLCCV51C3ba', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('testuser', '2026-06-29 14:57:33.940916', 'testuser@example.com', '$2a$10$1/EoQJVbbVR3tYnSHMjadONbJH1mGpZ/P32wrcWXFAPqoDQVSYGi.', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('katia', '2026-06-29 15:09:10.175427', 'cvleba@gmail.com', '$2a$10$5WU.Wj3PfECpiZH0p.BXYuHgkC0xoCW4Ym39X1CyAzvANnSaKZbNu', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('subtest', '2026-07-02 16:32:23.149626', 'subtest_88426@example.com', '$2a$10$Nq02YLmE6h/lz8o6t0vOI.RLy7ocse7viFdGs6NDLq7yKtnci6bB.', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('mario', '2026-08-05 18:13:43.615724', 'mario@example.local', '$2a$10$ClTmuTvRdQ0SQ39JG9Qfb.BZhofmsfGFqH2prcFBzP168W1.Bwf06', NULL, NULL);
INSERT INTO public.app_users (username, created_at, email, password_hash, reset_token, reset_token_expiry) VALUES ('luigi', '2026-08-05 18:13:43.821569', 'luigi@example.local', '$2a$10$HO5w7vI4sQTOKIUjZclWkO2u/r2V2.NHV9gyZo.jkA1A9XReyDw8S', NULL, NULL);


--
-- Data for Name: budget_events; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('2061f9cb-9acb-4717-9e1c-444468f92633', 120.00, '2026-06-29 12:22:04.258842', 'Unicredit', 89, '2026-06-29', 'DEBT_CREATED', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('b7525f44-0096-4637-be42-08889391613b', 84.00, '2026-06-29 12:31:08.690581', 'Volo America', 12, '2026-06-29', 'DEBT_CREATED', 'kat', '2026-01', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('e4979094-ea7e-49c2-a19b-c39c6794f088', 883.00, '2026-06-29 12:31:47.671264', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('a2a80663-133e-4450-98e1-291eb6a12d3d', 883.00, '2026-06-29 12:35:13.772436', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('47bf5727-b4dd-4894-9a35-a0ae1a4e4b09', 883.00, '2026-06-29 12:37:34.340065', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('9d4e9068-7122-44f5-b8e3-230d6f7c208c', 184.00, '2026-06-29 12:43:42.083129', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('0bf43c05-1f9e-43b7-b376-0dffeacf4603', 184.00, '2026-06-29 12:44:12.842831', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('7f4f3ef4-ae9f-4add-958c-7b64c7b75893', 184.00, '2026-06-29 12:45:02.158695', 'Uni', 1, '2026-06-29', 'DEBT_CREATED', 'kat', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('bdaaa56d-f027-4407-ba69-c72316e9ca93', 6.00, '2026-06-29 12:45:58.167815', 'HBO', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('0134e8dc-b341-421a-b03d-a78bd4b049b3', 6.00, '2026-06-29 12:46:05.997919', 'Ricarica', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('fef5fe3e-b0b5-44be-a01a-9645870ab53f', 12.00, '2026-06-29 12:46:27.03323', 'Microsoft Game', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('cbc05fae-e8dc-4fca-ac48-27f68a298e0f', 10.00, '2026-06-29 12:46:34.172553', 'Paypal', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('4cbdcf04-ffb0-4b49-9ea9-319727bf5ca6', 18.00, '2026-06-29 12:46:46.728001', 'Amazon music', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('d1e8a0d2-b165-453f-ac79-d4b9b9aaef70', 7.00, '2026-06-29 12:46:53.268977', 'Disney', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('27cad14e-1581-4834-bb45-5d4c43c4ece2', 7.00, '2026-06-29 12:47:02.02502', 'Netflix', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('1e5ed406-ed53-402c-9c13-35665d4ed707', 11.00, '2026-06-29 12:47:12.883671', 'DC fumetti', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('73f196d2-ff14-4dcf-b59b-28e3e80b7520', 11.00, '2026-06-29 12:47:22.235954', 'Marvel fumetti', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('42a58e4c-b812-4024-b924-caaa0954ff05', 21.00, '2026-06-29 12:47:31.181182', 'Gemini', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('394eed21-0c10-4176-8cd6-0104e6f7ad99', 23.00, '2026-06-29 12:47:39.873133', 'Capcut', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('be14287e-5e92-4101-bfb8-8ecad92118c2', 11.00, '2026-06-29 12:47:48.030018', 'C.ai', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('7b03c5dd-4c77-4e9b-aaf9-4d3f05a9d7db', 120.00, '2026-06-29 15:11:33.256306', 'Unicredit', 89, '2026-06-29', 'DEBT_CREATED', 'katiavalentini99@gmail.com', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('3db2a537-5e21-4764-9ea0-b65c786ca541', 84.00, '2026-06-29 15:12:01.235289', 'Volo America', 12, '2026-06-29', 'DEBT_CREATED', 'katiavalentini99@gmail.com', '2026-01', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('1423c91a-0885-43e7-aaad-b3f8b4fec2d8', 184.00, '2026-06-29 15:12:19.792912', 'Uni', 1, '2026-06-29', 'DEBT_CREATED', 'katiavalentini99@gmail.com', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('ea4a7b36-aeb8-4f1f-8c24-3a7898b4df28', 883.00, '2026-06-29 15:12:32.991391', 'Flexia', NULL, '2026-06-29', 'FLEXIA_SET', 'katiavalentini99@gmail.com', '2026-06', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('d6f844dd-e79f-444a-acc5-a7a65fb9b6cf', 6.00, '2026-06-29 15:13:21.7872', 'HBO', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('20d7d1cd-5e19-4f52-8e4f-bf31bc7a1e0e', 6.00, '2026-06-29 15:13:37.483564', 'Ricarica', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('b255b3c3-db87-4faa-bd1b-d0e0bc612432', 15.00, '2026-06-29 15:13:45.290935', 'Salmoraghi', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('ed3c2b07-6821-426f-8ef7-d5222aa6beee', 12.00, '2026-06-29 15:13:57.230179', 'Microsoft games', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('8866a587-ced3-4c96-ab1a-7bdd9d50c03f', 10.00, '2026-06-29 15:14:04.294673', 'Paypal', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('ee92f2a7-4c25-4b4f-a192-8b554126562d', 18.00, '2026-06-29 15:14:13.494258', 'Amazon music', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('263bdc71-a1fd-4832-8780-a9e9cadf2745', 7.00, '2026-06-29 15:14:20.630876', 'Disney', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('c5955429-6916-47a4-884a-0a408323c57d', 7.00, '2026-06-29 15:14:27.815517', 'Netflix', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('dccf3fbc-9d4b-4027-8705-ebbee79978ba', 11.00, '2026-06-29 15:14:42.027095', 'DC comics online', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('72b52a92-544b-4a47-a52a-6d49e6ca63ec', 11.00, '2026-06-29 15:14:51.059869', 'Marvel Comics online', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('5ab99316-4327-4240-8733-c185ecba1ad6', 21.00, '2026-06-29 15:15:00.045551', 'Gemini', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('c4bae364-9d6e-43c8-9540-4d9a2ad2cc26', 23.00, '2026-06-29 15:15:08.14113', 'Capcut', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('49a7b633-a4df-4a21-b4d4-63a60be62447', 11.00, '2026-06-29 15:15:12.766882', 'C.ai', NULL, '2026-06-29', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-2026-07-6dd04486-00d6-45a1-8718-6253a0a7cabc', NULL, '2026-07-01 09:34:59.059545', 'Chiusura automatica', NULL, '2026-07-01', 'MONTHLY_CLOSE', 'kat', '2026-07', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-2026-07-b2c1943e-82e7-48b4-8352-df08fd150f2c', NULL, '2026-07-01 09:34:59.093983', 'Chiusura automatica', NULL, '2026-07-01', 'MONTHLY_CLOSE', 'katiavalentini99@gmail.com', '2026-07', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('b1fd44dc-bdf6-453f-895f-7f2d5a7c0ca3', 184.00, '2026-07-01 10:37:58.457731', 'Uni', 1, '2026-07-01', 'DEBT_CREATED', 'katiavalentini99@gmail.com', '2026-07', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('6e6c9253-da05-4d94-b0d4-a6b9b6c6b3b3', 9.99, '2026-07-02 16:32:23.514794', 'Netflix-Test', NULL, '2026-07-02', 'SUBSCRIPTION_ADDED', 'subtest_88426@example.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-subtest_88426@example.com-2026-07', NULL, '2026-07-02 16:32:25.128803', 'Chiusura automatica', NULL, '2026-07-01', 'MONTHLY_CLOSE', 'subtest_88426@example.com', '2026-07', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('4a85d8cb-90be-4968-8cce-4b4281047b6d', NULL, '2026-07-02 16:44:58.262598', 'Salmoraghi', NULL, '2026-07-02', 'SUBSCRIPTION_REMOVED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('5a76380f-9bee-4a44-8c0d-5c8c478939dd', NULL, '2026-07-02 16:45:50.290645', 'Capcut', NULL, '2026-07-02', 'SUBSCRIPTION_REMOVED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('9d2851ec-362a-4429-8432-1ccfa59d7484', 18.50, '2026-07-03 09:22:45.35666', 'Pillola ', NULL, '2026-07-03', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('c28af095-4a6e-4acb-a827-3730f4b879ef', NULL, '2026-07-06 10:36:45.750777', 'Microsoft games', NULL, '2026-07-06', 'SUBSCRIPTION_REMOVED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('9d130630-42f5-4df6-8b8e-69d37f0f28ce', 3.00, '2026-07-06 10:37:40.239572', 'Annullamento abbonamento Microsofr', NULL, '2026-07-06', 'INCOME', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('52382b6c-dd5f-4408-9d12-98d29881d097', 15.00, '2026-07-13 09:10:51.568861', 'SalentoComics', NULL, '2026-07-13', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('0b16da9e-23a1-4556-a8a1-6b84666b57be', 14.00, '2026-07-17 16:19:51.076894', 'Janitor', NULL, '2026-07-17', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('33a07600-889c-4ac9-ac6a-d938d70b6620', 14.00, '2026-07-17 16:20:11.317807', 'Janitor.ai', NULL, '2026-07-17', 'SUBSCRIPTION_ADDED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('15504890-3ec0-403f-8b2d-eb853deac71e', 82.00, '2026-07-21 11:05:15.284716', 'Spesa per mamma', NULL, '2026-07-21', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('d2ca29c5-44b4-45ff-8c4e-437c8e2ea139', 11.00, '2026-07-21 14:35:13.239001', 'Cinema', NULL, '2026-07-21', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('afc814b6-d155-4bc6-9a93-b227d6930f1e', 3.00, '2026-07-22 11:05:30.167147', 'Bibita', NULL, '2026-07-22', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('8d708c98-ae1c-4307-be6b-c6140ad187ea', 2414.00, '2026-07-23 10:44:40.410751', 'Stipendio', NULL, '2026-07-23', 'INCOME', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('7ba3b84e-e3af-4514-a9ae-b60240627ec7', 15.00, '2026-07-24 18:12:34.151721', 'Kit Pandora', NULL, '2026-07-24', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('cb88a5f9-53e5-4d8b-859b-25c5eefd8506', 25.00, '2026-07-25 21:54:36.162221', 'Creme viso', NULL, '2026-07-25', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-kat-2026-07-30-9250926d-2c37-4de3-be2b-46af7634eca6', 2736.00, '2026-07-30 09:58:41.149267', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-06-30', 'BALANCE_CARRYOVER', 'kat', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-07-30-f812b620-f82f-45ff-8120-2713b1836c58', 2736.00, '2026-07-30 09:58:41.469984', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-06-30', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('fa839a06-bedc-4e28-922c-1cf4015df273', 290.00, '2026-07-30 11:47:33.037937', 'IELTS per magistrale', NULL, '2026-07-30', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('9e4f6f95-0dca-4eb7-9214-c373e632f31b', 33.00, '2026-07-30 13:09:17.119464', 'Ielts', NULL, '2026-07-30', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-07-31-8508650a-f453-4cf6-9bce-52007451b6d8', -48.00, '2026-07-31 01:14:59.665647', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-01', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('bf96616f-8e74-474c-9e53-a22056b1ebcf', 45.00, '2026-07-31 11:39:58.950943', 'Pillole ', NULL, '2026-07-31', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('ffa1c495-78d6-49db-bc1e-a2d31a383d9e', NULL, '2026-07-31 11:40:07.521528', 'Pillola ', NULL, '2026-07-31', 'SUBSCRIPTION_REMOVED', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('8eade427-76d8-4fc4-81d5-40faac9ff976', 15.00, '2026-07-31 12:11:20.452676', 'Spiderman Film', NULL, '2026-07-31', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-08-01-c30bd3db-c82b-4b34-96fe-e2a4dd16ad45', -273.00, '2026-08-01 09:13:59.556026', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-02', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-katiavalentini99@gmail.com-2026-08', NULL, '2026-08-01 09:13:59.633953', 'Chiusura automatica', NULL, '2026-08-01', 'MONTHLY_CLOSE', 'katiavalentini99@gmail.com', '2026-08', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('269673a9-ed00-4249-bec4-0c4b398dfea8', 41.00, '2026-08-01 09:14:14.188547', 'Libri ielts ', NULL, '2026-08-01', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-subtest_88426@example.com-2026-08', NULL, '2026-08-01 09:26:56.880342', 'Chiusura automatica', NULL, '2026-08-01', 'MONTHLY_CLOSE', 'subtest_88426@example.com', '2026-08', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('monthly-close-kat-2026-08', NULL, '2026-08-01 09:26:57.052241', 'Chiusura automatica', NULL, '2026-08-01', 'MONTHLY_CLOSE', 'kat', '2026-08', NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('be06e140-43d3-436d-8237-e507c8579f74', 175.00, '2026-08-01 21:58:55.269394', 'Spese generali', NULL, '2026-08-01', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-08-02-ddfc7e93-e9be-490d-b075-d2feb24b993f', 38.00, '2026-08-02 01:14:52.686843', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-03', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-08-03-5b9fff3a-34de-4943-a964-74c4a1c1f12e', -18.50, '2026-08-03 01:15:00.245866', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-04', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, NULL);
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-08-04-5b0829bd-ecb8-470b-a12b-dbd932b73846', -85.00, '2026-08-04 10:15:07.948314', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-05', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, 'Carryover');
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('carryover-katiavalentini99@gmail.com-2026-08-05-08c9b944-7611-45ee-994c-696984c002b5', -5.00, '2026-08-05 07:34:59.689073', 'Saldo consolidato movimenti oltre 30 giorni', NULL, '2026-07-06', 'BALANCE_CARRYOVER', 'katiavalentini99@gmail.com', NULL, 'Carryover');
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('1170f390-6135-4f65-93c2-a47436f9127c', 30.00, '2026-08-05 07:35:28.530518', 'Uscita', NULL, '2026-08-05', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, 'Svago');
INSERT INTO public.budget_events (id, amount, created_at, description, duration_months, event_date, type, username, year_month, category) VALUES ('6b3570ea-15c5-4a99-b05d-3971db15e02c', 300.00, '2026-08-05 18:07:08.342058', 'Deposito salvadanaio: Volo Corea', NULL, '2026-08-05', 'EXPENSE', 'katiavalentini99@gmail.com', NULL, 'Salvadanaio');


--
-- Data for Name: calendar_events; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (1, '2026-06-29 14:43:42.22491', '2026-06-30', 'Chiamare ginecologa', 'kat', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (2, '2026-06-29 15:10:08.747015', '2026-06-30', 'Chiamare Ginecologa', 'katiavalentini99@gmail.com', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (3, '2026-06-29 15:12:59.917635', '2026-06-30', 'Chiamare Tristano Leo', 'katiavalentini99@gmail.com', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (4, '2026-06-29 15:16:44.10712', '2026-09-26', 'Psicologa', 'katiavalentini99@gmail.com', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (6, '2026-07-13 14:12:37.908134', '2026-07-13', 'Chiamare segretaria Fedeli', 'katiavalentini99@gmail.com', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (7, '2026-07-24 18:11:55.944504', '2026-07-27', 'Appuntamento oculista', 'katiavalentini99@gmail.com', NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (8, '2026-07-28 09:55:44.213355', '2026-08-27', 'Visita oculistica Fedeli', 'katiavalentini99@gmail.com', '16:30:00', 'HEALTH', NULL);
INSERT INTO public.calendar_events (id, created_at, event_date, title, username, event_time, event_type, reminder_minutes) VALUES (9, '2026-07-29 12:28:10.334422', '2026-08-31', 'Appuntamento con Provenzano', 'katiavalentini99@gmail.com', '10:30:00', 'PERSONAL', NULL);


--
-- Data for Name: category_limits; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.category_limits (id, category, monthly_limit, updated_at, username) VALUES ('927d9681-9f39-441a-91ec-3a4a1e98836e', 'Svago', 100.00, '2026-08-05 07:35:51.622263', 'katiavalentini99@gmail.com');


--
-- Data for Name: savings_goal_transactions; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.savings_goal_transactions (id, amount, created_at, event_id, note, savings_goal_id, username) VALUES ('47c3f612-adf2-4370-a327-08fdf0284d7b', 300.00, '2026-08-05 18:07:08.306374', '6b3570ea-15c5-4a99-b05d-3971db15e02c', 'Versamento quota', '305e6140-38bc-4c27-a423-d1a652fc0b20', 'katiavalentini99@gmail.com');


--
-- Data for Name: savings_goals; Type: TABLE DATA; Schema: public; Owner: budget
--

INSERT INTO public.savings_goals (id, created_at, current_amount, icon, name, target_amount, target_date, username) VALUES ('305e6140-38bc-4c27-a423-d1a652fc0b20', '2026-08-05 17:01:40.987039', 300.00, '🎯', 'Volo Corea', 1500.00, '2026-12-01', 'katiavalentini99@gmail.com');


--
-- Name: calendar_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: budget
--



--
-- Name: app_users app_users_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.app_users
    ADD CONSTRAINT app_users_pkey PRIMARY KEY (username);


--
-- Name: budget_events budget_events_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.budget_events
    ADD CONSTRAINT budget_events_pkey PRIMARY KEY (id);


--
-- Name: calendar_events calendar_events_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.calendar_events
    ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);


--
-- Name: category_limits category_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.category_limits
    ADD CONSTRAINT category_limits_pkey PRIMARY KEY (id);


--
-- Name: savings_goal_transactions savings_goal_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.savings_goal_transactions
    ADD CONSTRAINT savings_goal_transactions_pkey PRIMARY KEY (id);


--
-- Name: savings_goals savings_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: budget
--

ALTER TABLE ONLY public.savings_goals
    ADD CONSTRAINT savings_goals_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--


